### ISSUE TITLE
Slightly misleading install instructions for vim

### ISSUE THREAD

**Issue by rogerdahl** [dracula/vim#154]
Thanks for the theme. It's awesome:)

I found the instructions at https://draculatheme.com/vim/ under `if you aren't so clever` a bit misleading. Since it doesn't include a git command and links directly to the `dracula.vim` file, I thought that was the only file I thought I needed and that the talk about setting the runtimepath to dracula was about setting it to the `dracula.vim` file.

This might be too quick and dirty, but worked for me:

```
git clone https://github.com/dracula/vim.git ~/dracula
rsync -r  ~/dracula/ ~/.vim
```

**Comment by benknoble** [comment]
Ah, yes. That old baggage. I don’t expect many people to manage plugins so manually. But yes, we need to get it removed or updated.

**Comment by rogerdahl** [comment]
I'm new to vim and haven't started using plugins, so didn't know about the path managers. That might be the case for most people that end up in the manual install section. If it doesn't make much sense to not use one these days, it's probably best to just remove the section and direct new users towards doing it through a plugin manager.

**Comment by dsifford** [comment]
I fixed this already. Must not have been pushed out yet.


https://github.com/dracula/dracula.github.io/pull/94

**Comment by benknoble** [comment]
@rogerdahl FWIW, I've been using vim for 4 years and still don't use a plugin manager. I use `*packages*` and git submodules to manage everything

**Comment by benknoble** [comment]
Yeah @dsifford I think the website team is really slow to do regeneration of the website (I believe it happens manually, which is a shame)

**Comment by dsifford** [comment]
> FWIW, I've been using vim for 4 years and still don't use a plugin manager. I use *packages* and git submodules to manage everything

You rebel! 😝
